### ISSUE TITLE
Repeated text (and column) numbers

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#11]
repeated text (and column) numbers used to be removed; I can imagine that this is not possible anymore (e.g., P. Amh. 2. 77; P. Ammon 3)? This probably is one of the things we just have to accept?
(If it would be possible, one should keep in mind that they do have to be repeated, between round brackets, on a new page. Cf., e.g., BL 12, p. 23-24.)

**Comment by jcowey** [comment]
Would be nicer if it could be made to work, but should be lower priority

**Comment by jcowey** [comment]
Example BL 12 pp. 16-17 BGU 940.

**Comment by Edelweiss** [comment]
Folgeinformationen in Klammern:

![bildschirmfoto 2017-07-07 um 17 15 13](https://user-images.githubusercontent.com/612862/27964283-ffda82ec-6337-11e7-8efe-d32368616e4f.png)
