### ISSUE TITLE
Double square brackets

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#13]
In several places a wrong font / character was used for the double square brackets, causing too much interlineary space.
Instead of correcting all these one by one in the system, I am hoping you could find and change them all automatically.

Example with the wrong brackets: p. 57, Chartae 524 several lines
Example with the right brackets: p. 59, P. Col. 5.1 Vo 4, 29

**Comment by jcowey** [comment]
Chartae 524
147.142.225.252/bl/app.php/correction/show/545

**Comment by jcowey** [comment]
(ἄρ.) ι⟦β η̣’⟧ \δ/  𐅸 ι̣ϛλο̣, 

⟦ ⟧

**Comment by jcowey** [comment]
Corrected by Cisca. Now fine. Can be closed.

**Comment by jcowey** [comment]
Am now closing.
