### ISSUE TITLE
Wrong order in P. Col. 5 (pp. 58 through 64)

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#14]
The problem of wrong order in P. Col. 5 (pp. 58 through 64) is easily solved when, just like in BL 12 p. 53, the part Vo 2 etc. (now in front of line no separated by comma) is moved to the Text Nr. column (and in bold print), so, instead of P. Col. 2
   1     Ro 5             >  1  Ro 5    (no line nr)
   1     Vo 2, 218     >  1  Vo 2      218
and so on until p. 64 P. Col. 5
   1     Vo 4, 85,86  >  1  Vo 4      85,86
   1     Vo 5             >  1  Vo 5      (no line nr)
When that is changed, the line numbers will be automatically in order.

**Comment by Edelweiss** [comment]
1001 Text contains "1" , Zeile contains "Vo 5"
should be
1001 Text contains "1 Vo 5" , Zeile empty

**Comment by Edelweiss** [comment]
Key will then look like this
```
e00277000t00000001p00000000sV°f00000004c00000000l00000171
```

**Comment by jcowey** [comment]
Cisca is going to change this is the system.
