### ISSUE TITLE
Order of P. Lond.

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#15]
To get the order of P. Lond. right, would it perhaps help if you change the order of the columns (so left: column with text nrs, middle: column with page nrs, right: column with line nrs)? Because they have to be in the order of text nrs, cf. BL 12.

**Comment by Edelweiss** [comment]
order by text number, not by page

**Comment by Edelweiss** [comment]
see print preview for P. Lond. 1-3

http://147.142.225.252/bl/app.php/report/print/13/253
http://147.142.225.252/bl/app.php/report/print/13/254
http://147.142.225.252/bl/app.php/report/print/13/255

**Comment by jcowey** [comment]
Yes the ordering is now fine.

**Comment by Edelweiss** [comment]
Still some problems with BL 14, though:

http://147.142.225.252/bl/app.php/correction/show/6149
http://147.142.225.252/bl/app.php/correction/show/6153

But of course this has no priority right now.
