### ISSUE TITLE
Header anpassen

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#18]
- auf der zweiten Seite ebenfalls auslassen (wie auf Seite 1)
- tiefer (näher an die Tabelle rücken)
- zwischendrin wiederholen z.B. nach Allgemeines
  - allerdings nicht, falls am Seitenanfang (Postscriptum oder händisch bei Löschung wegen Seitenverschiebung)
- falls P. Alex, P. Lond, O. Tait am Seitenanfang, Seitenkopf entsprechend ändern (Postscriptum)

**Comment by Edelweiss** [comment]
Zweite Seite für Allgemeines

- 16x24cm Portrait
- Margins 2cm left,  2,3cm right, 2,5cm top, 1,5 cm bottom
- Page layout: only right
- Header
- Footer

**Comment by Edelweiss** [comment]
Tabellenüberschriften näher an Content rücken

![bildschirmfoto 2017-06-30 um 17 46 44](https://user-images.githubusercontent.com/612862/27743437-4bdfad9c-5dbc-11e7-892c-6729a9b33035.png)

**Comment by Edelweiss** [comment]
Zwischenüberschriften bei Wechsel des Tabellenformats (dreispaltig, vierspaltig, z.B. nach Allgemeines, vor P. Alex, nach P. Alex, vor P. Lond 1, nach P. Lond. 3 usw.)
Eingefügte Tabellenüberschriften beziehen sich auf alle nachfolgenden Tabellen und sind deswegen keiner einzelnen Tabelle zugeordnet:

![bildschirmfoto 2017-06-30 um 18 59 07](https://user-images.githubusercontent.com/612862/27746232-aefca128-5dc6-11e7-9e3f-297dadd8a3f1.png)

**Comment by Edelweiss** [comment]
Seitenheaderwechsel bei P. Alex, P. Lond. 1-3 und O. Tait. 1, zum Beispiel:

![bildschirmfoto 2017-07-04 um 15 03 31](https://user-images.githubusercontent.com/612862/27831257-2e8f853a-60ca-11e7-8d03-271580111e7d.png)

**Comment by Edelweiss** [comment]
Verschiedene Header, je nach Content am Seitenbeginn

![bildschirmfoto 2017-07-04 um 15 02 09](https://user-images.githubusercontent.com/612862/27831358-a1a8bfaa-60ca-11e7-9565-391ef836ad45.png)

**Comment by jcowey** [comment]
High fives! That looks excellent, many thanks.
