### ISSUE TITLE
Spacing of entries 

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/beehive#21]
The spacing of entries for P.Alex., P.Lond. 1-3, O.Tait 1 is now not the same as the rest. The space between each entry is slightly bigger than elsewhere.
Would be good if it were the same as the rest. That is with less space.
P.Alex. p3
P.Lond. 1-3 pp125-128
O.Tait. 1 pp289-290

**Comment by Edelweiss** [comment]
![bildschirmfoto 2017-06-30 um 16 35 48](https://user-images.githubusercontent.com/612862/27740430-4b15b078-5db2-11e7-8b7c-408c1b57209b.png)
