### ISSUE TITLE
Neues Datenbankfeld für »pages«

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#27]
Es existiert noch kein Datenbankfeld für die Aufnahme von der Zahl der Seite, auf der »correction« in der Printversion erschienen ist.

Wie soll dieses Feld aussehen? Genügt ein einfacher Integer?

**Comment by jcowey** [comment]
If you are talking about the MySQL/Symphony database for BL, then the field called "Seite" is what I use to indicate the page number in an entry to BL.

See e.g. http://147.142.225.252/bl/app.php/tm/32720

**Comment by Edelweiss** [comment]
Oh, ich sehe es. Das Feld ist neu und heißt `compilationPage`.

**Comment by Edelweiss** [comment]
Warum ist `compilationPage` als String definiert und nicht als Integer? Hatten wir dafür einen bestimmten Grund?

**Comment by Edelweiss** [comment]
https://github.com/Edelweiss/beehive/commit/d624685596c0909cf20d8525b3b5106a7a4a976b

https://github.com/Edelweiss/beehive/commit/1e97c241d8c1a24cd5068d1335543213882e60ef

**Comment by Edelweiss** [comment]
https://github.com/Edelweiss/beehive/commit/d624685596c0909cf20d8525b3b5106a7a4a976b

https://github.com/Edelweiss/beehive/commit/1e97c241d8c1a24cd5068d1335543213882e60ef
