### ISSUE TITLE
Change Title in specific records

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/beehive#49]
In:  http://beehive.zaw.uni-heidelberg.de/correction/show/13747; http://beehive.zaw.uni-heidelberg.de/correction/show/13748; http://beehive.zaw.uni-heidelberg.de/correction/show/13749

would you please change

60000 = BASP

to

60000 = BASP 50

This is something, I am fairly sure, that I cannot do in the live version of "prod"

**Comment by Edelweiss** [comment]
Erledigt, es liegen keine weiteren Datensätze vor, die der editie 60000 = BASP zugeordnet sind. Soll/kann editie »60000 = BASP« gelöscht werden? (And never come back, gollum)

**Comment by jcowey** [comment]
60000 = BASP can and should indeed by deleted, never to come back :)

**Comment by Edelweiss** [comment]
»60000 = BASP« ist gelöscht
