### ISSUE TITLE
Clean up of description in BOEP records

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/beehive#50]
Take this example: http://beehive.zaw.uni-heidelberg.de/correction/show/13349

`αὐτὰς→λυπὰς (l. λοιπὰς), P. Heilporn (as reported in APIS)`

should be

`αὐτὰς → λυπὰς (l. λοιπὰς), P. Heilporn (as reported in APIS)`

in other words there should be a whitespace before the sign `→` and a whitespace following it. In all instances in BOEP files we should have X` → `Y.  In other words: "whatever" whitespace `→` whitespace "whatever"

Can you find a clever way of cleaning those up with regex or whatever? If it is possible, would you please carry out that clean up, across all BOEP files in Berichtigungsliste.

**Comment by Edelweiss** [comment]
alle Vorkommen ersetzt
