### ISSUE TITLE
Add running numbers to BOEP 11

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/beehive#54]
The file 101709.xml may be found at sd18K003/www/boep/101709.xml

Here you will find the following structure:

```XML
<row xml:id="boep1430" n="1430">
   <cell style="text-align: left;">
      <ref target="http://papyri.info/ddbdp/basp;59;68_1">BASP 59 68_1</ref>
   </cell>
   <cell style="text-align: right;">4</cell>
   <cell style="text-align: left;">[ὁ Μα]ρεψῆμις → [Μα]ρεψῆμις, N. Gonis</cell>
</row>
```

Value of n gives you the running number. Value of target gives you the match to BL database register_id

**Comment by Edelweiss** [comment]
Arbeitssheet:

https://docs.google.com/spreadsheets/d/1_DYpEzUmvw62x3rVV-EPkPUbPo_C8kYoYUaS5QZLsaI/edit?gid=1101761468#gid=1101761468

ok; bitte prüfen

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90532

number should be 1461

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90567

number should be 1496

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90569

number should be 1498

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90579

Number should be 1508

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90580

Number should be 1509

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90581

Number should be 1510

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90582

Number should be 1511

**Comment by jcowey** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/info/90584

Number should be 1513

**Comment by jcowey** [comment]
Otherwise fine. Thank you.

**Comment by Edelweiss** [comment]
changed; bitte prüfen

**Comment by jcowey** [comment]
Checked and now fine. Many thanks.
