### ISSUE TITLE
Verlinkung zu anderen Papy-Projekten

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#57]
z.B. in TM-View (auch bei HGV, DDB etc.) Links zu 

- papyri.info
- Trismegistos

für BOEP Links zu

- Pylon (only possible for BOEP 10 and BOEP 11 - for earlier BOEPs do not try to do anything)

**Comment by Edelweiss** [comment]
Link zu TM korrigieren

**Comment by Edelweiss** [comment]
ok; bitte prüfen

**Comment by jcowey** [comment]
Yes this is fine.
