### ISSUE TITLE
Sicht auf einzelne Korrekturen für unangemeldete Nutzer

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#59]

**Comment by Edelweiss** [comment]
angefangen, work in progress

**Comment by Edelweiss** [comment]
ok; bitte prüfen

Testlinks:

https://beehive.zaw.uni-heidelberg.de/dev/info/693
https://beehive.zaw.uni-heidelberg.de/dev/info/4605
https://beehive.zaw.uni-heidelberg.de/dev/info/90501
https://beehive.zaw.uni-heidelberg.de/dev/info/14124

**Comment by jcowey** [comment]
I am not so sure about how these are displayed. Something to discuss.

**Comment by Edelweiss** [comment]
Titelzeile: BL-Eintrag zu B.G.U. 1 12, 31 in BL XV S. 0 (BL-Online-Id 12345)

**Comment by jcowey** [comment]
Looks good. I am happy with this now. We make clear what it is and therefore my misgivings about placing of the information is no longer important in my opinion. Thank you.
