### ISSUE TITLE
Order ‘Allgemeines’ alphabetically

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#6]
- π/
- Eirenarchie
- x-δραχμ.
- ἀλλόφυλος
- ἀμφοδαρχία
- γῆ ὑπόλογος
- Δομιτιανός
- ἐν Ἀρ( )
- Ἡράκληος
- Καισάρειον
- καταμήνιοι
- ὁ ἐπὶ τῶν κατὰ τὴν Θηβαίδα / θηβάρχης
- ὀθόνιον
- οἰνάριον
- παρὰ τῷ κυρίῳ θεῷ
- πάρολκος
- πρεσβύτερος
- συντελεστής

**Comment by jcowey** [comment]
This is now fine

**Comment by jcowey** [comment]
Am now closing.
