### ISSUE TITLE
Neue Infotexte für verschiedene Landing Pages

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#60]
z.B. für Ghostwords Hinweis bzgl. "work in progress"

**Comment by Edelweiss** [comment]
Für Ghostwords etc.:

Die Listen sind noch unvollständig und noch nicht einzelnen Korrekturen zugeordnet. Sie werden kontinuierlich erweitert und sollen langfristig auf die Korrekturen verweisen, auf die sie sich in den jeweiligen Bänden beziehen.

**Comment by Edelweiss** [comment]
Noch nichts für:

[BOEP](https://beehive.zaw.uni-heidelberg.de/dev/collection/BOEP)
[BOEP doc.](https://beehive.zaw.uni-heidelberg.de/dev/collection/ddb)
[BOEP lit.](https://beehive.zaw.uni-heidelberg.de/dev/collection/dclp)

**Comment by jcowey** [comment]
BOEP:

Es ist jetzt möglich, alle BOEP-Korrekturen an einem Ort einzusehen. Diese sind alphabetisch nach ihrer BL-Abkürzung geordnet. Es ist nicht mehr notwendig, jedes einzelne BOEP zu überprüfen. Die laufenden Nummern sind nachträglich hinzugefügt worden.

**Comment by jcowey** [comment]
BOEP doc.:

Alle Korrekturen im BOEP, die dokumentarische Texte betreffen, sind an einem Ort gesammelt. Sie sind alphabetisch nach ihrem BL-Kürzel geordnet.

**Comment by jcowey** [comment]
BOEP lit.:

Alle Korrekturen im BOEP, die literarische und halbliterarische Texte betreffen, werden an einem Ort gesammelt. Sie sind alphabetisch nach ihrem BL-Kürzel geordnet.

**Comment by jcowey** [comment]
Fine
