### ISSUE TITLE
BOEP doc. + lit.

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#63]
lefty, righty, generell

**Comment by Edelweiss** [comment]
Titel ändern:

DCLP-Einträge in der Berichtigungsliste > BOEP-DCLP-Einträge in der Berichtigungsliste
DDB-Einträge in der Berichtigungsliste > BOEP-DDB-Einträge in der Berichtigungsliste

Lefty:

Titel ändern

BL > BOEP

Righty:

Fitern  nach BOEP

**Comment by Edelweiss** [comment]
Oder vielleicht lieber:

DCLP-Einträge in der Berichtigungsliste > DCLP-Einträge in BOEP
DDB-Einträge in der Berichtigungsliste > DDB-Einträge in BOEP

**Comment by Edelweiss** [comment]
ansonsten ok; bitte prüfen

**Comment by jcowey** [comment]
Yes please use your suggested: DCLP-Einträge in BOEP and DDB-Einträge in BOEP

**Comment by Edelweiss** [comment]
ok; bitte prüfen

**Comment by jcowey** [comment]
Yes looks good.
