### ISSUE TITLE
lists of "Online-Beständen"

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/beehive#68]
https://beehive.zaw.uni-heidelberg.de/dev/tm/5138

Berichtigungsliste – Online
TM 5138

Die Inhalte der angezeigten Korrekturen stammen aus den Online-Beständen von [BL XIII](https://beehive.zaw.uni-heidelberg.de/dev/bl/13) , [BL XII](https://beehive.zaw.uni-heidelberg.de/dev/bl/12) , [BL XIII](https://beehive.zaw.uni-heidelberg.de/dev/bl/13) , [BL IX](https://beehive.zaw.uni-heidelberg.de/dev/bl/9) , [BL XIII](https://beehive.zaw.uni-heidelberg.de/dev/bl/13) , [BL IX](https://beehive.zaw.uni-heidelberg.de/dev/bl/9) , [BL XIII](https://beehive.zaw.uni-heidelberg.de/dev/bl/13)

the above list seems to be constructed from the right hand list of the source - avoiding repetition of BL XIII S. 110 etc. but repeating BL volumes in the order they appear.

It would be nice if this was presented as [BL IX](https://beehive.zaw.uni-heidelberg.de/dev/bl/9) , [BL XII](https://beehive.zaw.uni-heidelberg.de/dev/bl/12) , [BL XIII](https://beehive.zaw.uni-heidelberg.de/dev/bl/13)

Here it would only be one mention of each used BL volume and presented "chronologically" from BL I through to BL XIII

That would be nice, if it is not too difficult to programme.

**Comment by Edelweiss** [comment]
bitte prüfen

**Comment by jcowey** [comment]
I am getting a runtime error at present

**Comment by jcowey** [comment]
Looking good now. The way that BL volume numbers are mentioned once only and ordered from I - XIII in the correct order is great.

https://beehive.zaw.uni-heidelberg.de/dev/tm/8976

has both BL and BOEP. I am wondering whether BOEP should just be mentioned once alone without any further details (no numbers - I am thinking of BOEP as being BOEP All). Not completely sure about this yet.

**Comment by jcowey** [comment]
This is now fine. I note that BOEP is listed without its number. That is good, thank you.
