### ISSUE TITLE
Hinweisetexte für Archiv

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#69]
https://beehive.zaw.uni-heidelberg.de/dev/archive

Vor allem BL Konk.

**Comment by Edelweiss** [comment]
Platzhalter in Template templates/default/archive eingefügt:

INFOTEXT ARCHIVE BL
INFOTEXT ARCHIVE BL KONK.
INFOTEXT ARCHIVE BOEP

https://github.com/Edelweiss/beehive/blob/symfony5/templates/default/archive.html.twig

**Comment by jcowey** [comment]
Archive BL:

Der gesamte Inhalt von BL I-XIII kann eingesehen und durchsucht werden. Die Quelle der Bände I-XI ist die BL-CD. Daher gibt es immer noch Tippfehler und bestimmte Ungenauigkeiten, die vom Ausgangsmaterial übernommen wurden. Die Einträge sind nicht mit den gedruckten Bänden abgeglichen worden. Die Fehler können im Laufe der Zeit in der Datenbank korrigiert werden. Diese Korrekturen durchzuführen wird davon abhängen, daß Benutzer die Fehler mitteilen. 
Korrekturen, die nicht in BL XIII enthalten sind, aber für künftige Bände gesammelt werden, sofern sie in der traditionellen Form erscheinen, können ebenfalls eingesehen und durchsucht werden. Diese sind keineswegs vollständig.

**Comment by jcowey** [comment]
Archive BL Konk:

Hier finden sich nur die in den beiden BL-Korkordanz-Bänden gefundenen und auf die BL-CD übertragenen Korrekturen. Diese sind nicht mit den gedruckten Bänden abgeglichen worden.

**Comment by jcowey** [comment]
Archive BOEP:

Es ist nun möglich, alle BOEP-Korrekturen in der normalen papyrologischen Reihenfolge der veröffentlichten Serien anzuschauen. Es ist nicht mehr notwendig, jedes einzelne BOEP zu überprüfen. Die laufenden Nummern wurden rückwirkend hinzugefügt.

**Comment by jcowey** [comment]
Fine
