### ISSUE TITLE
Weitere identifier und Links

### ISSUE THREAD

**Issue by Edelweiss** [Edelweiss/beehive#72]
Weitere identifier und Links: HGV 8898 = [TM 8898](http://www.trismegistos.org/text/8898) = [chr.wilck;;184](https://papyri.info/hgv/8898)

Umstellen zu:

[*] TM 8898 = [*] chr.wilck;;184 = HGV 8898

[*] => Symbol für externe Seitelinks (Auge)

**Comment by Edelweiss** [comment]
umgestellt und neues Icon; bitte prüfen

**Comment by jcowey** [comment]
This now looks good. I am closing
