### ISSUE TITLE
Return message that ddb-hybrid, tm, hgv, bl-bandnummer does not exist in the database

### ISSUE THREAD

**Issue by jcowey** [Edelweiss/beehive#75]
When using the Schnellsuche, if I enter a number (e.g. 15134), which does not exist in the database (register_id, I think), please return a clear message that what has been searched for does not exist in the database.

At present I get a 500 error message:

<img width="1589" alt="Screenshot 2024-09-10 at 11 35 27" src="https://github.com/user-attachments/assets/ed972227-24d3-426e-b2fa-21666a3ca045">

Das gesuchte "15134" ist in der Datenbank nicht vorhanden.

Or something like that.

**Comment by Edelweiss** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/register/10802

**Comment by Edelweiss** [comment]
https://beehive.zaw.uni-heidelberg.de/dev/tm/15134

**Comment by Edelweiss** [comment]
ok; ziemliche viele Änderungen für die Darstellung von Datensätzen durchgeführt; bitte umfangreich prüfen.
